### ISSUE TITLE
Styles aren't applied until editor opening

### ISSUE THREAD

**Issue by voviks21** [webextensions/live-css-editor#10]
Saved styles being applied only after click on extension icon. As Live-CSS-Editor is a best replacement for "Stylebot" extension, having "apply custom CSS before page load" option would be very useful and highly appreciated.

**Comment by paras20xx** [comment]
Thanks for the feedback :-)

I have reopenend https://github.com/webextensions/live-css-editor/issues/2 with a comment and marking this issue resolved as duplicate.
