### ISSUE TITLE
Editor in external window is not closing sometimes upon refreshing the page

### ISSUE THREAD

**Issue by webextensions** [webextensions/live-css-editor#106]
As per the feedback from Maxwell Hibbert on Chrome Web Store:

> Works really well overall. The only issue I have is when editing in an external window, the plugin has to be loaded again after refreshing the page I'm styling, and then I have to close the old editor. That quickly gets tedious.

**Comment by webextensions** [comment]
@ Maxwell Hibbert

Thank you for your feedback 🙏

**The expected behavior is that if one refreshes the page or navigates away, the external window should get closed. As per your message, it appears that it is not happening. Can you confirm that?**

We tried to reproduce it, but haven't been able to do so in general.

Not sure, but probably once we were able to reproduce it. And maybe, using the "Pin" feature (Apply styles automatically) once made the issue go away (probably because of additional permissions). Upon trying again (even after uninstalling and reinstalling the extension), we were not able to reproduce it. So, we are not sure about the issue we observed then.

**Can you help us in providing the steps to reproduce the issue?**
Also, can you try to enable the "Pin" feature (Apply styles automatically) and see if the issue goes away. Note: Enabling the "Pin" feature would request for additional permissions.

**Comment by maxwellhibbert** [comment]
Ah yes, enabling "pin" allows the external window to close on refresh 👍

Is there any way I can set it up to remain active after refresh, so I can continue to code?

Right now the flow isn't great because I often have markup changes and have to refresh, but that means activating the plugin again after refresh, and then resizing and moving the popup window.

**Comment by maxwellhibbert** [comment]
Scratch that, it's not closing reliably. If I refresh straight after loading the extension it's fine, but something else is preventing it closing after I work for a bit. If I get some time I'll try figure out what it is.

**Comment by webextensions** [comment]
Hmm ... That is weird. We will keep an eye open in case we observe this issue again.

Another theory, when you are observing this issue, is it like you are also doing JavaScript debugging (via breakpoints / debugger) around that time?

**Comment by webextensions** [comment]
> Is there any way I can set it up to remain active after refresh, so I can continue to code?

There is intention to bring such a feature, but as per the current situation, it might take some time (a few months minimum) because the current implementation of external window is not designed in a very thoughtful manner and it deserves refactoring to cover a variety of use cases (eg: Data consistency when editor is open in/for multiple browser tabs).

Also, if you can describe a bit more about your use case, maybe there could be alternative solutions/approaches which might turn out to be more generic.

eg: Are you using the external editor because you are designing for mobile/smaller devices and hence you are using browser DevTools to reduce the size of the page? Maybe, in that case, if this extension is available as a tab within the browser DevTools, maybe that would help in solving your use case in even better way.

**Comment by maxwellhibbert** [comment]
> eg: Are you using the external editor because you are designing for mobile/smaller devices and hence you are using browser DevTools to reduce the size of the page? Maybe, in that case, if this extension is available as a tab within the browser DevTools, maybe that would help in solving your use case in even better way.

I am using an external window for exactly that reason :)

Having access within devtools might be good, but I do reference the dom, styles and console frequently, so having a separate tab to access back and forth might create too much friction. The additional window is kind of ideal, when it works.

In the meantime, I'm going to play around with some scripts to automate things a bit - find and close the old editor window, relaunch the extension and position the new window where I need it.

Thanks for a really useful extension btw. When I have to work on things that can only be served live, I find it essential.

**Comment by webextensions** [comment]
Right, so editor within DevTools may not serve perfectly well when floating editor might be better.

Probably some users also find approach of Amino Editor https://chrome.google.com/webstore/detail/amino/pbcpfbcibpcbfbmddogfhcijfpboeaaf better (pop-up editor window next to extension icon). You may wish to try out that or similar other tools if they fit fine for your usage.

Regarding the use case that you have described, we will keep that in mind while designing architectural updates to keep data in sync with multiple editors for same site/origin (maybe then we wouldn't need to close the external window).

**We shall keep this issue open for now, to identify and fix the issue when one refreshes the page or navigates away, the external window is not getting closed.**

**Comment by maxwellhibbert** [comment]
Thanks for the reply. I have tried the suggested extension, but have randomly lost work using it and sometimes it stops functioning until a full restart of Chrome is performed. It also doesn't support emmet, which becomes frustrating quickly ;)

I've just put together a workflow in Alfred with some cobbled together applescript that makes sure to load your extension in an external window on my second display. Works well so far.

**Comment by webextensions** [comment]
@maxwellhibbert 

The root cause was seemingly the fact that the extension's background page/scripts were getting closed/disconnected after some inactivity.

This issue should be fixed along with various other updates which will be included with the release of https://github.com/webextensions/live-css-editor/releases/tag/v8.21.2 once it becomes available in coming days/weeks (v8.21.2 has been submitted to Chrome Web Store).

**Comment by maxwellhibbert** [comment]
That's great news, thanks 👍

**Comment by webextensions** [comment]
@maxwellhibbert

The latest version is available now in Chrome Web Store. We hope that the UX has improved now. 😀
