### ISSUE TITLE
Suggestion : give the possibility to show the live editor in a separated window

### ISSUE THREAD

**Issue by funkycram** [webextensions/live-css-editor#11]
Problem : Live CSS editor show on top of the website you are working on.
In some cases, it takes to much place, and even if you resize it to make it small and push it at the right, bottom, left or right, it hides to much the website you are working on.

Example : you push Live CSS editor at the bottom of your website : when you scroll down at the maximum, you cannot see the footer of your website.

Suggestion  : possibility to show it in a separated window or possibility to divide the window in 2, as the native browser web editor does. If you show it in a separated window, and have 2 screens, you can show the website in a screen and the CSS editor in an other.

**Comment by webextensions** [comment]
Thanks for the report :-)

Just want to know your use case a little more. Are you using it along with browser developer tools and that's why the window/viewport effectively gets reduced in size. And Magic CSS also consumes some space which you wish to avoid.

Would the following solutions be fine:
- Provide a minimize button
- When the mouse moves out of the viewport (html/body element), reduce the opacity of the floating editor to 0.1 or 0. We might add that as a configurable setting.

**Comment by funkycram** [comment]
Opacity reduction when mouse moves out the viewport would be great ! The worse case is when I develop for mobile, I need to use the adaptative view and there is nearly no space left for the viewport.
Thanks a lot !

**Comment by paras20xx** [comment]
The issue has been resolved and you can set the option to hide the editor on mouse out by:
"+" > More options > Experimental options > Hide editor when mouse pointer is outside the webpage

Note that mouse support is required for this feature to work, i.e., in Chrome, you are supposed to use the "Responsive" mode with "Device type" set as "Desktop". If the "Device type" option is hidden in your dev tools, you will need to activate it (by clicking on three-vertical-dots > Add device type).

The latest version of the extension (v6.2.33, with this fix included) for Chrome would be available in a few minutes.

**Comment by webextensions** [comment]
Also, auto live reloading of modified CSS files would be added in coming days/weeks. With that, you will be able to edit and save the project files in your favorite code editor and Magic CSS would reload them immediately.

That would be equivalent to what you were initially asking (editing code outside the browser tab).

**Comment by webextensions** [comment]
@funkycram 
The feature of editor in external window is now implemented and the publish has been initiated on Chrome Web Store for the latest version (v8.9.0). It should become available within next few hours/days.

**Comment by funkycram** [comment]
Brilliant! Thanks a lot!
