### ISSUE TITLE
Feature: Add option to change font size and font family in the editor

### ISSUE THREAD

**Issue by pranayrauthu** [webextensions/live-css-editor#12]
I want to customize the font used in the editor. I think it would be really nice if there are fields for font-size and font-family in the options.

**Comment by paras20xx** [comment]
@pranayrauthu 
Hi ... thanks for the suggestion :-)

Can you describe your use case a little more?
Is it something among the following, or something else:
- You are using it on a high resolution / low resolution screen and it appears too small / too large
- You don't like the font
- You don't find the syntax highlighting to be good enough
... something else?

**Comment by pranayrauthu** [comment]
Yea exactly I use multiple monitors font size looks to be really small in one of them. Also, I want to modify the font style used in the editor to some other monospaced font.

**Comment by webextensions** [comment]
@pranayrauthu 
I have prepared most of the changes required for implementing customize-able font-size. The changes should be released soon (in a few days/weeks) for Chrome along with some other unrelated improvements.

Note: I'll be adding the customize-able font-size, but would not be adding the monospace-font-family-change option. The main reason being that it doesn't seem to provide much utility at the current scale of this extension. In case font change is still required, one may use **chrome://settings/fonts > Fixed-width font**.

**Comment by webextensions** [comment]
The issue has now been fixed with https://github.com/webextensions/live-css-editor/commit/fb453a97e0db12b064fbafaec2aeb49575ffff10

The fix is available with the latest version of Magic CSS (v7.0.0) on Google Chrome.
For the other browsers, the update would be published later on.
