### ISSUE TITLE
Shortcut Does Not Work Second Time

### ISSUE THREAD

**Issue by spieglio** [webextensions/live-css-editor#13]
Just discovered this in replacement of a different Live CSS Editing Extension. So good to finally have code completion.

I, however, found that the shortcut apparently only works two times. First to activate the extension first. And then it deactivates the code. But then it doesn't do anything any more 🙈.

Hope to see further improvements on this. It's an amazing tool.

Thanks,

Chris

**Comment by webextensions** [comment]
@spieglio

**Probably you just need to click the "Activate code" icon** (the one which looks like a red color circle).

Hope this fixes your problem :-)

**Explanation of the behavior:**

The shortcut (or clicking on the extension icon) does one of the following things:
1. Initiating the floating editor if it is the first time you are running it for that tab page
2. Reinitiating (disable CSS and reposition near top-left of page) the floating editor if it is already open.
3. Showing the floating editor if it was opened previously and then closed (by clicking on the "cross" icon or by pressing the "Esc" key).

If the floating editor is already open, generally, you don't need to press the shortcut again :-)

**Why do we temporarily disable the CSS when the user clicks on extension icon again?**
It is possible that sometimes a user would (unintentionally) type some CSS which can break the extension's UI badly. eg: div {display: none;}

In such a case, if you click on the Magic CSS icon (or use the shortcut key), the case 2 happens (disable CSS and reposition near top-left). This way, the user can fix that CSS and click the "Activate code" icon.

**Comment by spieglio** [comment]
I see this behavior. Thanks for the explanation. I thought it would toggle between active/deactivate CSS changes. That's what sprout the confusion for me.

**Comment by spieglio** [comment]
I think that would be a lovely idea. Making it useful in every moment. And it can at the same time still do the other things.

**Comment by webextensions** [comment]
Fixed in https://github.com/webextensions/live-css-editor/commit/99153a70bc4539dbf89837e1638a36a2f0f39e39

It would work when the next update of the extension gets released.

**Comment by spieglio** [comment]
Nice, I'm looking forward to it.
