### ISSUE TITLE
Release a version on GitHub without dynamic permissions to support browsers which don't support dynamic permissions

### ISSUE THREAD

**Issue by webextensions** [webextensions/live-css-editor#143]
eg: Kiwi browser

Ref:
* https://github.com/kiwibrowser/src.next/issues/98
* https://github.com/kiwibrowser/src.next/issues/211

Added a TODO note at https://github.com/webextensions/live-css-editor/commit/ecf1bde599bd7dbf52450187f021a92d898a7bcb

**Comment by webextensions** [comment]
The workaround version with static permissions is available at https://github.com/webextensions/live-css-editor/releases/tag/v8.22.5

**Comment by webextensions** [comment]
@Kaloogh26
Thank you for your report :raised_hands:

Please note that the release version has been updated to avoid a config loading related error log that you had added in your report. Previously, a local setup behavior was getting triggered since the extension in Kiwi browser is being loaded in `Developer mode`.

But, based upon usage, there may still be some error log entries which might be seen in the Developer mode in the Kiwi browser. Many of them usually tend to be non-critical errors/logs. As long as you don't observe any functionality issues, those can be safely ignored. For now, we recommend to ignore them because many of them might have been already handled and those logs would be false alarms. Also, it is a bit time consuming to do debugging in Kiwi browser :sweat_smile:

**Comment by webextensions** [comment]
@Kaloogh26
Yet another update has been made and the release version has been updated at https://github.com/webextensions/live-css-editor/releases/tag/v8.22.5

This update solves the issues related to reapplying styles and loading the extension in a new browser instance (previously, it would load only when one manually goes to the Extensions page with Developer mode for each new browser instance).

There may still be some other issues when running this extension in the Kiwi browser, eg: related to UI/UX for small screen sizes. Feel free to create new issues in this project regarding any bugs you observe.

Thanks again :smile:

**Comment by Kaloogh26** [comment]
Funciona perfectamente no encontré ningún problema, gracias por actualizar :)
