### ISSUE TITLE
Apply style automatically not working on Chrome 127.0.6533.120

### ISSUE THREAD

**Issue by presedo** [webextensions/live-css-editor#145]
I installed the [live-css-editor-for-kiwi-browser-v8.22.5](https://github.com/webextensions/live-css-editor/releases/tag/v8.22.5) version which was working fine until the latest Chrome update.

I see the message "You need to provide permissions to reapply styles automatically.
If you wish to use it for a niche browser, like Kiwi Browser, then we recommend you to go to the [Releases page for this extension](https://github.com/webextensions/live-css-editor/releases)."

**Comment by webextensions** [comment]
Thank you for the report @presedo 

We are able to reproduce the issue if the mouse moves slightly between click down and click up. Apparently, that slight mouse move is triggering some logic in the recent Chrome browser which is treating the upcoming permissions dialog as a potential security-issue / irritating-ux-issue and hence blocks the upcoming dialog with a message/reason like saying 'This function must be called during a user gesture'.

While we attempt to dig further and fix the issue, for the time being please try the operation again while attempting to not let the mouse move.

A quick question, why did you install the "Kiwi" browser version on Chrome? For the Chrome browser, we would recommend to download it from https://chromewebstore.google.com/detail/live-editor-for-css-less/ifhikkcafabcgolfjegfcgloomalapol . Did our message in that dialog lead you to install that version? If that is the case, then we shall improve our error message there.

**Comment by webextensions** [comment]
It appears to be a regression from the browser's end.

Ref: https://issues.chromium.org/issues/355266358

The bug has been fixed for the upcoming versions of Google Chrome / Chromium and the fix may not be backported to the current version (version 127).

For the time being, kindly try the operation while attempting to not let the mouse move even by 1 pixel during that click operation.

In the meanwhile, we will attempt to add a note/warning message for the users in the cases where they might be potentially affected.

**Comment by presedo** [comment]
> message

Hello
Yes, I installed both Kiwi and non kiwi extensions.
The mouse "trick" didn't worked for me (or maybe I didn't get it right)
So if this is an issue from Chrome, I'll wait until it's fixed.

**Comment by webextensions** [comment]
@presedo 
The bug seems to have been fixed with the latest version of Chrome (v128) as we have been able to verify it on Ubuntu and Windows.

Closing this issue.
