### ISSUE TITLE
Live editor for CSS, Less & Sass

### ISSUE THREAD

**Issue by SimpleUs** [webextensions/live-css-editor#19]
Стили применяются с некоторой задержкой,т.е.на секунду проскакивает оригинальный стиль.
Styles are applied with some delay, i.e. the original style slips for a second(Stylebot in this plan works instantly)

**Comment by webextensions** [comment]
@SimpleUs 

Do you mean this part for the "Apply styles automatically" feature?
If so, then yes, it can be improved in some manner.

Or do you wish to report it for the delay in applying styles when typing?
If so, then the reason behind such delayed implementation helps in handling some performance and UX concerns. This part may not be changed unless there are good reasons to fix it or make it configurable.

**Comment by Laki6** [comment]
Hello,

What if
**Alt + ↑ key** or **Alt + ↓ key** could move **UP** or move **DOWN** the lines in the CSS editor?

**Comment by webextensions** [comment]
@Laki6 
Ctrl + Shift + ↑ key
and
Ctrl + Shift + ↓ key
would now move the lines UP and DOWN :)

**Comment by voviks21** [comment]
да, я тоже это заметил.
yes, I've noticed that too. There are 1-3 sec. delay before styles injected after page loaded. In other custom CSS extension "Stylebot", CSS applied instantly before page loaded.

**Comment by webextensions** [comment]
The issue of the delay has been fixed :-)
