### ISSUE TITLE
Syntax Highlighting feature.

### ISSUE THREAD

**Issue by Krato5** [webextensions/live-css-editor#20]
Hi,
 I have been working with this tool for a long time, and It will be really awesome if we can make the tool showing the default CSS block of the selected element of the page in that small window better than going to browser inspecter every time?

I really wish if the team have a planning behind this feature! keep it up !!

**Comment by Krato5** [comment]
@webextensions 
 ya well, this really seems to be challenging feature, the tool of CSS viewer is awesome also just wished if it was able to make a live edit of the css code not only show up in the console.

**Comment by voviks21** [comment]
@Krato5 I thought you mean showing where custom CSS for element are placed in extension editor window. That would be awesome too, if after selection element it will auto scroll to block related to selected element.

**Comment by webextensions** [comment]
@Krato5 
Upon reading your comments again, I realize that the "Suggested CSS Selectors" notification can also contain links to edit the file containing those selectors.

I had thought of doing it after implementation of live editing + saving of real CSS/Less/Sass files (reference: https://github.com/webextensions/live-css-editor/blob/master/TODO.md#new-features).

I have updated the above mentioned TODO list.
Marking this issue resolved for now. I'll revisit it once the "save file" task is completed.
