### ISSUE TITLE
Issues / frustration with freeform sizing - possible panel option?

### ISSUE THREAD

**Issue by clechner77** [webextensions/live-css-editor#21]
As I said in my review, I love the fact that the editor is freeform so it can be moved, etc, but it can be irritating having to always try to find the right place.  Adding the option to either be 1) always on top or even better 2) having it be in panel would fix this.  Note, with the panel option, we should have the option of having it be the default too, obviously.  

Does that make sense?

**Comment by webextensions** [comment]
Showing the editor in a separate panel would require refactoring and UX-wise I'm not sure how beneficial that would be.

For now, I have added the code to resize and/or reposition the floating editor panel (on window resize), if it goes out of viewport.

I hope this would reduce the pain-point of floating editor going out of view on opening debugger tools.

Marking resolved.

**Comment by clechner77** [comment]
Actually, this works pretty well and takes are of most of the difficulty when resizing.  It also seems to adjust to if you open/close chrome dev tools and then it overlaps with the editor.  Well done and thank you!

**Comment by webextensions** [comment]
Just now, I have made another patch release (should be available on Chrome store in a few minutes from now) with fixes for some edge cases related to auto-positioning and auto-resizing.
