### ISSUE TITLE
CSS IDs that start with "hex-code" are not being resolved properly

### ISSUE THREAD

**Issue by KaiReichart** [webextensions/live-css-editor#23]
I have an ID #d21_tooltip, and the the tool thinks it is a color.

<img width="312" alt="bildschirmfoto 2019-01-18 um 09 52 22" src="https://user-images.githubusercontent.com/29383712/51375676-d0e60500-1b06-11e9-83b2-701de05752ac.png">

**Comment by webextensions** [comment]
This issue originally belongs to the plugin https://github.com/easylogic/codemirror-colorpicker

This issue also exists in their current demonetization at https://colorpicker.easylogic.studio

I will an issue in that repository and link it here.

**Comment by webextensions** [comment]
This issue can be fixed once https://github.com/easylogic/codemirror-colorpicker/issues/31 gets resolved appropriately.

**Comment by webextensions** [comment]
The core issue in the other library has been resolved.

I'll be updating the usage in this extension :+1:

**Comment by webextensions** [comment]
@KaiReichart 
I have updated the library code to fix the issue.

The change would be available with the next release (sometime soon). Closing the issue.
