### ISSUE TITLE
No window after launching, CSS rules not saved

### ISSUE THREAD

**Issue by scrutinizer11** [webextensions/live-css-editor#24]
Hello,
1. It worked at first after I installed it however later it would show "Loading message..." without  window opening or with unreasonable amount of time passing since launching it.
2. Another issue is that it fails to save CSS rules. The rules get applied, I click the pin button. The message pops up "now you rules will be applied onwards without loading the extension" or smth to the effect however regardless of whether I pin or unpin, the next I time I open the site or the page the rules are gone. I double-checked every setting - it should hold the changes.

**Comment by webextensions** [comment]
@scrutinizer11 

Can you provide the steps to reproduce with the following details:
* Browser
* Website / Webpage URL
* Any relevant error messages in console

Other notes:
* Is this issue specific only to a particular website / webpage?
* Are you doing localStorage.clear() manually? (Internally, the extension uses localStorage to save the CSS changes)
* Are you using private browsing mode? (The localStorage would get cleared for a new session)

**Comment by scrutinizer11** [comment]
Chrome  49.0.2623.112 (64-bit) for Mac (10.7.5)
Any page
Nothing in console (other than "Navigated to" the URL)

No, it's common issue
No
No
It resets to site's CSSs as soon as you reload the page no matter what.
25.01.2019, в 11:07, webextensions написал(а):

**Comment by webextensions** [comment]
@scrutinizer11

Closing the issue as "Cannot Reproduce" due to lack of activity/response.
