### ISSUE TITLE
Removed styles

### ISSUE THREAD

**Issue by SimpleUs** [webextensions/live-css-editor#25]
After cleaning the local storage, the styles disappear. Other extensions "Stylebot", "Stylus" continue to preserve styles normally. Can this be fixed?

**Comment by webextensions** [comment]
@SimpleUs 
Technically, this can be done, but it may take time before I'm able to pick that up.

I've added a task for it in [TODO.md](https://github.com/webextensions/live-css-editor/blob/master/TODO.md#new-features)

Marking this issue closed.
