### ISSUE TITLE
Iframe styles aren't applied consistently

### ISSUE THREAD

**Issue by enteryournamehere** [webextensions/live-css-editor#26]
The extension does not always load the custom CSS for an iframe automatically (of course with 'Apply styles automatically' enabled). It does load the CSS when I click the extension.
The 'Load for frame/iframe' option in the extension settings is also enabled.

#### 'Apply styles automatically' disabled (= the normal page without custom CSS):
![disabled](https://user-images.githubusercontent.com/11255568/52533169-373dfc00-2d30-11e9-8fb0-384cdf053972.png)

#### With the option enabled:
![automatically applied](https://user-images.githubusercontent.com/11255568/52533177-50df4380-2d30-11e9-9cd9-5f8efbb9c06c.png)
Note that the custom CSS applies to the main page, but not to the iframe. (iframe src is from a different domain than the main page)

#### With the extension opened:
![opened](https://user-images.githubusercontent.com/11255568/52533179-589ee800-2d30-11e9-860c-b1df69a7c649.png)

The right frame in the screenshot is an iframe with as origin domain ivwebcontent.telegram.org. The frame at the left is just a text input, not an iframe, and not relevant to this issue.

After some testing I found out that when I load the page, then wait around 20-30 seconds, and then reload, the extension _will_ load the custom CSS for the iframes most of the time.

I am also seeing this error in the console sometimes. I haven't found a correlation between this and the custom CSS being applied, so I'm not sure if it's related.
![chrome_2019-02-10_12-42-38](https://user-images.githubusercontent.com/11255568/52533270-be3fa400-2d31-11e9-8a24-adad97d973a4.png)

## Steps to reproduce
0. Make sure 'Load for frame/iframe' is enabled in the extension settings.
1. Go to https://ivwebcontent.telegram.org/ and write some CSS for it using the Magic CSS extension. In my example I used `* { color: red; }` for easy testing.
Make sure the 'Apply styles automatically' option is enabled.
2. Go to https://instantview.telegram.org/contest/nos.nl/template35/issue1/
To verify that the custom CSS should apply to the iframes, click the extension icon to run it. The text of both iframes on the left should become red.
3. Reload the page. The text in the iframes _should_ be red, but (probably) is not.
4. Wait ~30 seconds and reload the page again. Again, the text in the frames should be red. I've had mixed results with this - on one device, this worked fairly consistently (css was applied most of the time), on another device it never worked (with the exact same extension settings). Both devices are laptops running Windows 10 + Chrome.

**Comment by webextensions** [comment]
@enteryournamehere 
When reapplying styles, the logic was looking only for the parent frame (the page/top-level-frame).
I have updated that part of the logic. It should now work fine.

The change would be available with the next release (sometime soon).
