### ISSUE TITLE
Feature req: Reset rules for the current webpage

### ISSUE THREAD

**Issue by benchesh** [webextensions/live-css-editor#30]
Loving this extension so far; I'd like to make a feature request.

Let's say I do something really stupid and set body{display:none} causing everything including the CSS editor to disappear. Ideally I'd want an easy way to remove this property without having to inspect the page.

I'd like to propose that (when active) rules can be disabled temporarily via the right click menu/browser button. Perhaps in addition I could be taken to a different page to edit the CSS externally. I think this would really add a lot to the extension.

All the best,
Ben

**Comment by webextensions** [comment]
@benchesh 
To get out of such situations, just click on the extension icon once again. This will disable the provided styles :-)

You may find more details/explanations around this behavior at https://github.com/webextensions/live-css-editor/issues/13#issuecomment-375788827

I believe it covers the scenarios you described. Marking closed.
