### ISSUE TITLE
Alt+Shift+S: In CSS mode, insert selector always at top-level

### ISSUE THREAD

**Issue by rillig** [webextensions/live-css-editor#32]
Place the text cursor in the middle of CSS code:

![image](https://user-images.githubusercontent.com/3233724/57549199-29196f00-7363-11e9-8c86-ba212287d97e.png)

Press Alt+Shift+S to select a page element.
Press Enter to use that element.

Expected: The new CSS rule is inserted so that it is syntactically valid.
Actual: The CSS rule is inserted at a point that would be valid for SCSS and SASS and LESS, but not for plain CSS:

![image](https://user-images.githubusercontent.com/3233724/57549333-8c0b0600-7363-11e9-9aef-fb6de3b18237.png)

**Comment by webextensions** [comment]
@rillig 
I have improved the logic of automatic cursor movement when using the generate CSS selector functionality. The logic is still simple and language agnostic. If the current cursor position is inside a curly brace ('{') section, it moves the cursor after the closing brace ('}').

The change would be available with the next release (sometime soon).
