### ISSUE TITLE
Emmets autocomplete

### ISSUE THREAD

**Issue by ktunprasert** [webextensions/live-css-editor#35]
Is it possible to have emmets-based autocomplete? I find myself accidentally writing emmets only to have been disappointed

**Comment by webextensions** [comment]
@ktunprasert 

The following commit in July, 2017 was the first one which added the support for Emmet based shortcuts:
https://github.com/webextensions/live-css-editor/commit/1c74430ead6d4d1d937f3fdc71c2663bad22fc34

It seems to be working fine for me. Kindly provide the steps to reproduce and the environment details.

**Comment by ktunprasert** [comment]
Sometimes when pressing `tab`, the autocomplete suggestion takes over instead for example if you type `fs`, it suggests `float-offset` which would've explained my confusion of why emmets is not working. I tend to use just the left-hand side shortcuts a lot, now that I am testing it again it does work if I cancel the suggestion. 

https://puu.sh/DFsQx/b75c7c136f.webm

This seems to be my misunderstanding, I thank you for pointing it out. I will disable autocomplete from now on.

**Comment by webextensions** [comment]
@ktunprasert 
I have now added an option to enable/disable CSS property-value autocomplete under "More options".

The change would be available with the next release (sometime soon). Closing the issue.
