### ISSUE TITLE
[bug] Styles can target the extension window itself - including display:none

### ISSUE THREAD

**Issue by Soninmyeyes** [webextensions/live-css-editor#40]
I was adding a `div` selector to a rule with `display: none` applied. Before I got a chance to specify an id, the display attribute kicked in and hid everything on the page--including the extension window itself.

I was able to use Chrome DevTools to bring the window back so I could fix the style, but in general, I think it would be good if the code editor window could be made immune to styles originating within itself that would hide the editor or otherwise render it unusable. (`display: none; visibility: hidden; opacity: 0; pointer-events: none; ` positioning it off-screen; z-index-ing it below other objects; etc.)

**Comment by webextensions** [comment]
@Soninmyeyes  
To get out of such situations, just click on the extension icon once again. This will disable the provided styles. Also, if the "Deactivate code" icon is visible, it can be used :-)

The same issue and current solution + possible solution + technical limitations are discussed in https://github.com/webextensions/live-css-editor/issues/13#issuecomment-375788827, https://github.com/webextensions/live-css-editor/issues/30 and https://github.com/webextensions/live-css-editor/issues/37

While such cases can be detected to a certain extent, any generic solution wouldn't cover all possible scenarios. eg: What if the user writes `div { display: flex }` and breaks the UI.

Later on, we may add some detection for such scenarios and disable CSS automatically. But, for now, current solution mentioned above works out well with a little learning curve for the user.

Marking this issue as closed.

**Comment by webextensions** [comment]
@Soninmyeyes 
The feature of editor in external window is now implemented (the editor in the external window is not affected by the bug you mentioned) and the publish has been initiated on Chrome Web Store for the latest version (v8.9.0). It should become available within next few hours/days.
