### ISSUE TITLE
Feature Request(s) - Dark Mode Support

### ISSUE THREAD

**Issue by Tantumonium** [webextensions/live-css-editor#45]
A) Support for a different extension icon color for use with dark web browser themes (black icon is almost invisible when using a dark browser theme).

B) Support for some different theme editor styles (e.g. Ambiance, Chaos, Chrome, Clouds, Clouds Midnight, Cobalt, Crimson Editor, Dawn, Dracula, Dreamweaver, Eclipse, GitHub, Green on Black, Gruvbox, idle Fingers, IPlastic, KatzenMilch, krTheme, Kuroir, Merbivore, Merbivore Soft, Mono Industrial, Monokai, Nord Dark, Pastel on dark, Solarized Dark, Solarized Light, SQL Server, Terminal, TextMate, Tomorrow, Tomorrow Night, Tomorrow Night 80s, Tomorrow Night Blue, Tomorrow Night Bright, Twilight, Vibrant Ink, Xcode )

**Comment by webextensions** [comment]
@Tantumonium 

I'll look into if/how the theme can be auto-detected and changed the icon color based on that.

Regarding themes, a dark theme might be added in future. There is a TODO task for this at https://github.com/webextensions/live-css-editor/blob/master/TODO.md

I am a bit reluctant to add support for so many themes (like you mentioned), considering the fact that it is more important to split the "editor" functionality and "apply css" functionality before such architectural changes can be done. And such major changes would require a lot of time, hence may not come in near future.

**Comment by webextensions** [comment]
Added light/dark theme support in the following commits:
* https://github.com/webextensions/live-css-editor/commit/4d08396480320160bfe0d691df4701c5a456e6ac
* https://github.com/webextensions/live-css-editor/commit/78a39b95422a128640f65b7d5a28fd93e05cbeb1

It is available in the latest version of the extension in Chrome Web Store.

For updating the icon, I have added a TODO note at:
* https://github.com/webextensions/live-css-editor/commit/6d36f7d6bc7357f18d23d2ff87726d9aed57e9d5

Marking this issue as closed.

**Comment by webextensions** [comment]
@Nikodemsky FYI :-)

**Comment by Nikodemsky** [comment]
> @Nikodemsky FYI :-)

That's great news! Now the extension needs only option to move window outside viewport(so i can code properly for mobile devices, while not covering half of the viewport - see attachment) and it's perfect.
![223](https://user-images.githubusercontent.com/14090596/96349476-3edea800-10b0-11eb-9505-8a3a6ac022cf.jpg)

**Comment by webextensions** [comment]
@Nikodemsky 

For the time being, you may find some workarounds and alternatives mentioned in:
* https://github.com/webextensions/live-css-editor/issues/36
* https://github.com/webextensions/live-css-editor/issues/11
* https://github.com/webextensions/live-css-editor/issues/21

It hasn't been done yet considering the current scope of the extension and the possible alternatives/workarounds. There is chance that in future, the scope of this extension would increase further and such use cases would end up being covered. But, it might take some time for that.

**Comment by webextensions** [comment]
@Nikodemsky 
The feature of editor in external window is now implemented and the publish has been initiated on Chrome Web Store for the latest version (v8.9.0). It should become available within next few hours/days.

**Comment by webextensions** [comment]
@Tantumonium 
A white colored icon has been added when the user prefers dark color scheme. The change would be available v8.14.0 onwards, which should be available in a couple of days on Chrome Web Store.

Please note that it would work as per https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-color-scheme and doesn't have capability to read the browser's "theme" color as such.

**Comment by Nikodemsky** [comment]
Any chance to change line numbers in dark mode to something a bit more visible? my suggestion is something like #808080

Also i think numbers column have some kind of box shadow over first character of the code itself? it looks weird... like first character have different color.
![333](https://user-images.githubusercontent.com/14090596/120955852-9cfcf000-c752-11eb-8b2c-8612266b140a.png)

**Comment by webextensions** [comment]
@Nikodemsky 
Thank you for the report :smiley:

The above mentioned issues have been fixed in https://github.com/webextensions/live-css-editor/commit/f80c458b49e5518e64e0c2d8d76580f71856f6b8 and https://github.com/webextensions/live-css-editor/commit/ea72bb1ad7c4e8436227dff4b7033a089d13a49e

The fixes would be available v8.14.2 onwards :thumbsup:
