### ISSUE TITLE
Error: EPERM: operation not permitted

### ISSUE THREAD

**Issue by martobg10** [webextensions/live-css-editor#47]
Hi,
This is the error I have. I tried with PowerShell, CMD, Node.js cm, but no difference.
![Annotation 2020-05-16 102242](https://user-images.githubusercontent.com/44940748/82113500-31b73900-975f-11ea-8a70-20bbe1f55a93.png)

**Comment by webextensions** [comment]
@martobg10 
I would recommend you to run it from your project. Which might be at some path like:
C:\Users\marto\projects\my-website

Running it from a folder, like the current one, containing thousands of files would also give you slow performance.
