### ISSUE TITLE
Firefox addon cannot be found

### ISSUE THREAD

**Issue by LeeteqXV** [webextensions/live-css-editor#49]
"Oops! We can’t find that page"
https://addons.mozilla.org/en-CA/firefox/addon/live-editor-for-css-less-sass/

Does not appear via search for "live css" within the Addons page either anymore.
Cannot seem to find it - not possible to install anymore?
What happened here?

**Comment by webextensions** [comment]
@LeeteqXV 

Sorry for the trouble. The review process for Firefox has been a bit too much complicated and time consuming. They eventually pulled down the extension (one of the major parts being that the Sass JavaScript should not be remotely loaded).

Once I have some time in hand, I'll try to upload the extension for review again (after gathering the original and unminified code for all the libraries being used).

In the meantime you can run the extension in development mode for Firefox by following the instructions provided at:
* https://github.com/webextensions/live-css-editor/blob/master/notes-for-developers.md
* https://github.com/webextensions/live-css-editor/blob/master/extension/README-FOR-EXTENSION-REVIEWERS.md#if-you-wish-to-build-a-zip-package-of-the-extension-on-your-own-from-the-git-repository-of-magic-css-project

I hope that helps.

Leaving the issue open for now. Will mark it resolved when the latest version gets published for Mozilla Firefox.

**Comment by muhammad-07** [comment]
Also removed from Edge store

**Comment by decembre** [comment]
Maybe can you post it here:
[add0n.com](https://add0n.com/index.html)

**Comment by XeroxDev** [comment]
Still not available :c hope it will come ASAP back to the store.

**Comment by webextensions** [comment]
Since many people are reporting this issue, we will try to spend some time on it soon + the time it takes for Mozilla to approve.

**Comment by tw0b1t5** [comment]
Hello! So, it's been a month since the last message here. Is there something new about this situation?

**Comment by webextensions** [comment]
@tw0b1t5 
We will try to update it in the coming days. Please note that the "Sass" support may need to be disabled for the time being (since that might cause a hurdle in the approval process).

**Comment by windmaomao** [comment]
Sass support might be minor. This is my #1 addon for firefox :)

**Comment by webextensions** [comment]
@LeeteqXV @muhammad-07 @decembre @XeroxDev @tw0b1t5 @windmaomao 

The Sass support has been removed and the extension is now available again for Mozilla Firefox at: https://addons.mozilla.org/en-US/firefox/addon/live-editor-for-css-less-sass/

Also, the extension has been published for (Chromium based) Microsoft Edge at: https://microsoftedge.microsoft.com/addons/detail/live-editor-for-css-less/ahibbdhoijcafelmfepfpcmmdifchpdg

The Sass support part would be handled separately.

Closing this issue.

**Comment by ktunprasert** [comment]
@webextensions the addon is gone again.

**Comment by paras20xx** [comment]
Reopening.

**Comment by XeroxDev** [comment]
What is the exact reason / why does Mozilla remove this addon in the first place?

**Comment by paras20xx** [comment]
@XeroxDev 
In Firefox addon store (and similarly for other browsers), the full source code goes through a review process. A good chunk of this extension's files are various popular and not-so-popular third-party libraries. For the review process, we need to provide the reference to the source code. Even though that part is done (eg: via github commit based path), they suggest us to share the links from some more standard paths (eg: via github release tag based path). Since there are too many entries and some of them had to be modified to support some of the required features, we need to update instructions at various places for the extension reviewers. We will try submitting it again this week.

Previously, there were issues with loading "Sass" from a remote source (which is technically, a valid security concern) and that was also disabled for Firefox.

**Comment by webextensions** [comment]
@LeeteqXV @muhammad-07 @decembre @XeroxDev @tw0b1t5 @windmaomao @CrazyHackGUT @ktunprasert @dustin555 @guilhermefront @diego-betto @girlandhercode

Sorry for the delay in attempting a fix for this issue in Firefox Add-ons Store.

The changes required by Mozilla review process are done and another submission is made. This time, we will ensure that the review process gets completed properly.

**If all goes well, the extension should become available at https://addons.mozilla.org/firefox/addon/live-editor-for-css-less-sass/ within next few hours/days.**
