### ISSUE TITLE
cursor becomes very large in css editor on some web sites - how can I reset it to normal small size?

### ISSUE THREAD

**Issue by david-edwards1** [webextensions/live-css-editor#57]

**Comment by david-edwards1** [comment]
![live-css-editor_GIANT_CURSOR_BUG](https://user-images.githubusercontent.com/69686648/93644065-dcb65880-f9c6-11ea-8d59-c4576054e28c.PNG)

**Comment by david-edwards1** [comment]
I have tried deleting the extension and re-installing it. It always fails on this site: https://assets.ctl.io/chi/3.0.0/getting-started/

**Comment by david-edwards1** [comment]
![image](https://user-images.githubusercontent.com/69686648/93644620-ff953c80-f9c7-11ea-8ae3-517141ceadba.png)

**Comment by webextensions** [comment]
@david-edwards1 

The issue has been fixed and would be available when the extension gets updated in Chrome Web Store.

In the meantime, you can copy-paste the following code in the affected webpage:

```
/* https://assets.ctl.io/chi/3.0.0/getting-started/ - Fix for too much whitespace */
#MagiCSS-bookmarklet .CodeMirror pre {
    padding: 0 4px;
    margin: 0;
}

/* https://assets.ctl.io/chi/3.0.0/getting-started/ - Fix for selection background not showing up */
#MagiCSS-bookmarklet .CodeMirror pre {
    background-color: transparent;
}
```
