### ISSUE TITLE
Magic CSS doesn't accept input in devtools responsive mode in Chrome

### ISSUE THREAD

**Issue by QuintinS** [webextensions/live-css-editor#6]
First off, amazing extension. Such an indispensable part of my workflow now, thanks so much for creating it!

After working perfectly in Chrome's mobile responsive preview mode since as long as I've been using it, today I started noticing that it doesn't accept keyboard input anymore on mobile mode on these Chrome builds:

- Chrome Version 60.0.3112.101 (Official Build) (64-bit)
- Chrome Canary Version 62.0.3194.0 (Official Build) canary (64-bit)

Sometimes input is accepted initially, but stops after changing tabs.

**Comment by webextensions** [comment]
Thanks for reporting :-) I'll try to replicate it and figure out the issue.

**Comment by webextensions** [comment]
@QuintinS I tried it a few times, but couldn't replicate it, probably because there might be some particular order of steps to be followed. Could you help me with the exact steps you follow when you face this issue?

I have tried it on Chrome 60.0.3112.101 on Ubuntu 16.04, which OS are you using?

**Comment by QuintinS** [comment]
On MacOS Sierra. Will try to replicate and send steps.

**Comment by webextensions** [comment]
@QuintinS Hey ... were you able to replicate the issue? :-)

**Comment by webextensions** [comment]
Closing the issue due to inactivity.

Feel free to reopen this with steps to replicate.
