### ISSUE TITLE
Firefox version seems to be broken

### ISSUE THREAD

**Issue by waitingmoon** [webextensions/live-css-editor#63]
The re-released Firefox version seems to be broken. When I press the add-on button, a loading message appears, but no editing window appears.

The #topCenterAlertNote is inserted into the html as many times as the button is pressed.

Version: 8.10.1

![livecss](https://user-images.githubusercontent.com/16256443/115487179-1e77ec00-a293-11eb-8f27-146db339733a.png)

**Comment by webextensions** [comment]
@waitingmoon 
Thank you for the report ... looking into it.

**Comment by webextensions** [comment]
Fixed the bug in https://github.com/webextensions/live-css-editor/commit/ec25e7c47573ff1730db3414e77c4c4253577129

The new version has been published to the Mozilla Add-ons Store. Please update.

@waitingmoon 
Thank you again :-)
