### ISSUE TITLE
Reload?

### ISSUE THREAD

**Issue by Nikodemsky** [webextensions/live-css-editor#66]
Two things:
1. Is there possiblity to reload current page WITHOUT reloading module(external window)? It would be really helpful in cases which i need to change html structure of the page.
2. Can you add option to "remember" that module should be opened in external window?

**Comment by webextensions** [comment]
@Nikodemsky 

1. There is a good chance that there would be architectural difficulties in implementing that with the current code base (which needs refactoring). Also, there might be some technical / security UX issues related to permissions, considering the fact that the extension requests for minimum permissions.
2. It might work out with relatively small changes, assuming no technical blockers for opening external editor (after a small delay).

If point 2 works out, it might be good enough for the time being.

Thank you for the report :smiley:

**Comment by webextensions** [comment]
@Nikodemsky 
The changes (for point 2) would be available with v8.16.0 which should be available on the Chrome Web Store in a few minutes/hours.

Marking resolved.
