### ISSUE TITLE
Uncaught Could not reach server

### ISSUE THREAD

**Issue by logovitta** [webextensions/live-css-editor#67]
I'm trying to use the file method with the chrome extension.
But it doesn't seems to work.
I have to insert the server address this way
![image](https://user-images.githubusercontent.com/57635138/122189528-4cdc0700-ce91-11eb-87c6-9c6a366ac927.png)
using http:// after the https://, otherwise it doesn't work, but when i try to select a file to use i got this console error
![image](https://user-images.githubusercontent.com/57635138/122189721-75fc9780-ce91-11eb-87a4-4fcb43def2be.png)
It's adding the https:// at the start of the request.
Also the live server is only http.... not https

**Comment by webextensions** [comment]
@logovitta 
You are right. It would probably be simple to use `http://` itself. After verifying any cases of potential permissions related issues, it should be a relatively quick thing to fix.

Note: Support for `https://` was not added to keep the implementation simple.

An update would be provided here soon.

**Comment by webextensions** [comment]
@logovitta 
The changes have been added in https://github.com/webextensions/live-css-editor/commit/9138330ce80078a989eec9cb2f80c7b1c39fb5f4 and it would be be available with v8.17.0 within a few hours / days.

If it doesn't work out well, please add a comment :thumbsup:
