### ISSUE TITLE
Curso doesn't show

### ISSUE THREAD

**Issue by docliving** [webextensions/live-css-editor#7]
Great extension !!!
I can't see the cursor when I'm editing the CSS.

Any clues how can I fix this.
Maybe changing the color of the cursor?

Thank you

Using Chrome Versión 61.0.3163.100 (Build oficial) (64 bits) in Spanish

**Comment by webextensions** [comment]
@docliving Does it happen only for some particular webpage or for any webpage you attempt to edit ?

**Comment by docliving** [comment]
Only for local files like
file:///C:/page.html

**Comment by webextensions** [comment]
The cursor is represented using a "div" element with class "CodeMirror-cursor".

I believe some style in your code must be over-riding the visibility related or border style for that element.

In case you are not able to figure it out, you may share the code of that page here for assisting you with the fix.

**Comment by webextensions** [comment]
Closing it under assumption that the problem was due to custom CSS styling.

If you still find something needs to be fixed in Magic CSS, feel free to comment here :-)

**Comment by docliving** [comment]
Good morning,
Sorry for the late replay, I had lots of work.

I found the solution: both divs should override "overflow" style set by users

`div.CodeMirror-cursors {`
`    overflow: visible !important;`
`}`
`div.CodeMirror-cursors >div.CodeMirror-cursor {`
`    overflow: visible !important;`
`}`


The bug happens if  div style is different than "visible like:
`div { overflow: hidden}`

Thanks again for sharing your work, it's a great extension

**Comment by webextensions** [comment]
@docliving
The following commit fixes it:
https://github.com/webextensions/live-css-editor/commit/33d8cd2db60f60301f31f015b1ba3fc3c574c8e6#diff-6f3538af89ff0b94e999beb87b7ac384

The updated version of the Magic CSS extension (v6.2.19) would be available on Chrome Web Store in a few minutes.
