### ISSUE TITLE
This site can’t be reached

### ISSUE THREAD

**Issue by DeanShiDirect** [webextensions/live-css-editor#74]
Hello, I followed the steps below:
![01](https://user-images.githubusercontent.com/94027516/148635520-f0e7a684-99c5-4ee3-a1a9-14e41f4ed38e.png)
![02 (1)](https://user-images.githubusercontent.com/94027516/148635540-f7e80dae-ed4f-489a-b845-8f3d3724e454.png)

when I go to http://192.168.0.64:3456/ on Google and Firefox, it shows "This site can’t be reached". 
![8151118 (1)](https://user-images.githubusercontent.com/94027516/148635550-2a1030d2-c895-4302-aaae-8fcf841b7578.jpg)
![108151153 (1)](https://user-images.githubusercontent.com/94027516/148635551-dd280e5d-4d15-4929-af6d-760473a1ab2d.png)

Then I changed the port from 3456 to 8081, also unavailable.

But I have made a live-server successfully like this.
![20108151917](https://user-images.githubusercontent.com/94027516/148635647-27cd3a02-c457-4730-887a-79505377ba86.jpg)

So what should I do?
There must be some errors in your project.
How should we correct them?

**Comment by webextensions** [comment]
@DeanShiDirect 
As per the error message (from browser screenshots), there seems to be some kind of redirect happening, which is unexpected.

When you run `$ live-css`, a few URLs are suggested in logs, eg: http://192.168.0.64:8081/ and 4 other such URLs there ... Can you confirm that none of those 5 URLs are working if you try to open them directly in the browser?

**Comment by DeanShiDirect** [comment]
![saddads](https://user-images.githubusercontent.com/94027516/148639203-985479ad-a926-44b1-87a7-02ea686a561c.JPG)
@webextensions tks for your reply. the same results. I will try later

**Comment by webextensions** [comment]
Did you change the port number in the configuration this time (the port number is different from last time, also the IP address seems to be a mix of two IP addresses from the old screenshot) ?

Can you share the following 3 together:
* The configuration file
* The whole output of the command
* The screenshot from browser

Also, can you ensure that the browser shows a different error message when the `live-css` server is not running (please attach that screenshot as well)?

**Comment by DeanShiDirect** [comment]
1. I download the files "live-css-editor-main" from Github
![1](https://user-images.githubusercontent.com/94027516/148711285-194ec617-d341-49e5-978f-3ab9e726eb60.jpg)

2. I get into the 'CMD'
![2](https://user-images.githubusercontent.com/94027516/148711293-1d0afe7e-be32-4d8f-83ae-917eedb21870.jpg)

3. write 'live-css' in CMD
![3](https://user-images.githubusercontent.com/94027516/148711295-d8543c3e-0c27-44f7-8d2c-8340fd6edbb9.jpg)

4. the file 'C:\Users\Administrator\Desktop\test\live-css-editor-main\live-css\test\sample-html'  can open like below
![4](https://user-images.githubusercontent.com/94027516/148711300-b8b79ee0-2aac-42ed-ab23-d89da5bde6a3.jpg)

5.http://127.0.0.1:8080/
![5](https://user-images.githubusercontent.com/94027516/148711303-08dec753-781e-4119-9347-2f65f0015163.jpg)

6.http://192.168.0.64:8080/
![6](https://user-images.githubusercontent.com/94027516/148711308-c679f15b-06c5-433b-8e13-1b3993185136.jpg)

7.http://198.18.0.78:8080/
![7](https://user-images.githubusercontent.com/94027516/148711311-7f06b05b-5653-453e-9329-181082cd76d6.jpg)

8.http://localhost:8080/
![8](https://user-images.githubusercontent.com/94027516/148711317-330fd394-8a21-4c9f-89c9-593e05f3498a.jpg)

9.http://windows10.microdone.cn:8080/
![9](https://user-images.githubusercontent.com/94027516/148711326-4c15d99c-08dd-474d-80a9-b0f6d05971ae.jpg)

10.the same files "\live-css-editor-main\live-css\test\sample-html", when I start the "live-server", it successed
http://127.0.0.1:8080/

![110101834](https://user-images.githubusercontent.com/94027516/148711484-51d83dd7-b8e3-47f4-bc43-242040d38309.jpg)

**Comment by webextensions** [comment]
In the logs, the `live-css` server suggests you to use the 8081 port, while in your browser, you are attempting to use port 8080.

Kindly try port 8081 in your browser for your current configuration and let us know if that works.

By default, the live-css server runs on a different port than your file server. So, for example, you may want to run your file server at port 8080 and live-css server at port 8081.

**Comment by DeanShiDirect** [comment]
> live-css
I think it's not the error of the port setting
I choose the 8081, also tried port 3456, both failed.
I'm going to uninstall and reinstall Live-css
![微信截图_20220110135107](https://user-images.githubusercontent.com/94027516/148723640-2243aa49-ac79-46dd-8507-69c3622b0a28.jpg)

![01](https://user-images.githubusercontent.com/94027516/148723642-6a98e71f-ff35-4c06-867b-2d561cd180b1.jpg)
![3](https://user-images.githubusercontent.com/94027516/148723645-5c7c4893-00de-408d-8938-7f2de7d034c8.jpg)
Anyway, thanks for your reply.
Have a nice day!

**Comment by webextensions** [comment]
Previously, I had commented:
> As per the error message (from browser screenshots), there seems to be some kind of redirect happening, which is unexpected.

:point_up_2: **A correction there:**
When live-css server is working well, accessing a path like http://127.0.0.1:3456/ would redirect to http://127.0.0.1:3456/live-css

@DeanShiDirect 
Something seems odd in the way the live-css server is working as per the screenshots you have shared. eg: When the configuration file is not provided it is expected to start at port 3456 rather than 8081 (which is happening in your case).

The http server indicating redirect, but not being able to load the final page is also weird.

**Can you connect over Twitter direct message at https://twitter.com/webextensions or suggest an alternative means to connect directly? Maybe we can have a screen sharing session to debug the issue?**

**Comment by DeanShiDirect** [comment]
@webextensions tks for your kindly reply. when port 3456 is unavailable, I tried other port like 8080 or 8081，but failed. When i am free, i'd love to solve this problem

**Comment by webextensions** [comment]
Sure :+1:

**Comment by webextensions** [comment]
Closing the issue due to inactivity. Probably it worked out :-)
