### ISSUE TITLE
Missing 'name' and 'description' in manifest.json inside the crx-file from Chrome Web Store

### ISSUE THREAD

**Issue by roarbr** [webextensions/live-css-editor#93]
Hi,

I'm mirroring some Chrome-extensions from a script using the ExtensionID from the Chrome Webstore. To obtain the name of the extension I unpack the crx-file with unzip and look into the "name" tag in the manifest.json file. For the other extensions I have downloaded, the "name", "version", and "description" tag are the same as in the Chrome Web Store.

But for this 'live-css-editor' extension the "name" and "description" tags contain the same placeholder as in the manifest.json in this git-tree.

Example:
Link to extension in Chrome Web Store:
https://chrome.google.com/webstore/detail/live-editor-for-css-less/ifhikkcafabcgolfjegfcgloomalapol

# Download crx-file for this extension:
curl -sSL "https://clients2.google.com/service/update2/crx?response=redirect&prodversion=107.0.5304.63&acceptformat=crx3&x=id%3Difhikkcafabcgolfjegfcgloomalapol%26uc" -o ifhikkcafabcgolfjegfcgloomalapol.crx

# Unpack the manifest.json
unzip -d . ifhikkcafabcgolfjegfcgloomalapol.crx manifest.json

# Display manifest.json:
cat manifest.json
{
  "update_url": "https://clients2.google.com/service/update2/crx",
  "version": "8.18.6",
  "manifest_version": 2,
  "author": "Priyank Parashar",
  "default_locale": "en",
  "name": "__MSG_Extension_Name__",
  "description": "__MSG_Extension_Description__",
  "homepage_url": "https://github.com/webextensions/live-css-editor",
...

See that the "name" and "description" contains the same placeholder as the source code:
https://github.com/webextensions/live-css-editor/blob/main/extension/manifest.json

# The manifest.json from 'React Developer Tools':
{
  "update_url": "https://clients2.google.com/service/update2/crx",
  "manifest_version": 2,
  "name": "React Developer Tools",
  "description": "Adds React debugging tools to the Chrome Developer Tools.\n\nCreated from revision 336ac8ceb on 7/13/2022.",
  "version": "4.25.0",
...

This extension (and other extensions I have downloaded) have a correct value in the "name" and "description" tags.

Is this an error in packaging the crx-file? Or is there any other reason why these tags are not set to the expected values?

**Comment by webextensions** [comment]
@roarbr 
The "MSG_" pattern used in those places is based on the localization/internationalization syntax for WebExtensions. So, for getting the applied values, one would need to parse the values from "_locales/en/messages.json" as well.

Ref:
* https://developer.chrome.com/docs/extensions/reference/i18n/
* https://developer.chrome.com/docs/extensions/mv3/i18n-messages/
* https://github.com/webextensions/live-css-editor/blob/main/extension/_locales/en/messages.json

Marking the issue as Closed.

If you have further queries, feel free to add a comment here or open a fresh issue.
