### ISSUE TITLE
Using Less: "each" undefined. Which version of Less is in use?

### ISSUE THREAD

**Issue by cilex-ft** [webextensions/live-css-editor#97]
Hi,

I'm in the tedious process of rewriting / refactoring years of css into a clean Less, and the extension is incredibly useful.

However, to write better code with Less, rather than just adapting existing lines of css, I tried to use [each function](https://lesscss.org/functions/#list-functions-each), which appeared in Less 3.7.0:

```
@selectors: blue, green, red;

each(@selectors, {
  .sel-@{value} {
    a: b;
  }
});
```

But Magic CSS display "Invalid LESS syntax, function 'each' is undefined".

Where can I see which Less version is used?

Do you plan to upgrade to a recent version?

EDIT: I just digged into your code and I think I found in the linked repo https://github.com/webextensions/less.js/blob/build-less-for-magic-css/package.json : `"version": "3.0.0-alpha.2"`?

So, do you please plan to upgrade ?

Or: is there any chance I'd be able to clone all this stuff and create an updated version for my Chrome 107(but, many other people could benefit from an "official" version..)?

**Comment by webextensions** [comment]
@cilex-ft 
Thank you for the report. We shall attempt an update of less and other packages in coming days/weeks.

Yes, we are using a slightly customized version of less@3.0.0-alpha.2. The customization is used for adding the sourcemap support, so that error details can be provided properly. Ref: https://github.com/webextensions/live-css-editor/blob/main/extension/scripts/3rdparty/basic-less-with-sourcemap-support.browserified.js.source.description.txt

Keeping this issue open for now.

**Comment by webextensions** [comment]
Added code for generation of bundles for usage with Magic CSS: https://github.com/webextensions/less.js/commit/1bf6a495a11dee77bb0f773149ff6261a4718c4d

Updated less.js to the latest version: https://github.com/webextensions/live-css-editor/commit/36d2c6d130e60084e90c9cf7ab3eb6cb9733aadc

The required changes are done :+1:

Please note that the detailed testing and verification is pending. Once done, we will submit the extension for an update.

**Comment by cilex-ft** [comment]
Great news! 

Can't wait to replace this ugly (but working) (but sub-maintainable) snippet in my .less file

```
        @objects: Foo, Bar, Baz;

        .-(@i: length(@objects)) when (@i > 0) {
            @name: extract(@objects, @i);
            //https://stackoverflow.com/questions/31779829/remove-space-when-less-variable-value-to-string
            @color: ~'var(--text-@{name})';
            .object.@{name}-item {
                border-color: @color;

                .header {
                   .icon:before {
                       background-color: @color;
                    }
                }                
            };
        .-((@i - 1)); //iterate
        } .-;  
```

**Comment by webextensions** [comment]
The change has been pushed to Chrome Web Store. Version 8.19.0 onwards, the extension would use the latest version of Less.js.

Please note that it may take time from a few hours to a few days before Chrome publishes the update.

This issue can be closed after the update is available :+1:
